### PR TITLE
Update ReadME

### PR DESCRIPTION
**Pull request by Frkovo**
Hi Anson, ChatGPT thought it is necessary for your repository to have a readme file. so i made one!

### CODE REVIEW

**Comment by Frkovo** [comment]
！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Review by Anson2251 — CHANGES_REQUESTED** [review]
no chatgpt please

**Comment by Frkovo** [comment]
ok i will use kimi ai

**Comment by Frkovo** [comment]
please merge my pull request
it fixed lots of problems

**Review by Anson2251 — COMMENTED** [review]
hahaha

**Comment by Frkovo** [comment]
Why not WTFPL
I love this LICENSE

**Review by Anson2251 — CHANGES_REQUESTED** [review]
Sorry, but this licence is good

**Comment by Frkovo** [comment]
I'm sad because u reject my pr :(

**Comment by Anson2251** [comment]
I'm sorry about that

**Pull request closed without merging**
